"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR/".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG","True")

ALLOWED_HOSTS = []
for allowed_host in os.getenv("ALLOWED_HOSTS", "").split(","):
    if allowed_host.strip():
        ALLOWED_HOSTS.append(allowed_host.strip())
    
CSRF_TRUSTED_ORIGINS = []
for csrf_trusted_origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(","):
    if csrf_trusted_origin.strip():
        CSRF_TRUSTED_ORIGINS.append(csrf_trusted_origin.strip())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    
    # swagger 
    'drf_yasg',
    
    # Cors Header
    "corsheaders",

    # Text Editor
    'tinymce',

    'accounts',
    'shop',
    'comments',
    'orders',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Cors header middleware
    "corsheaders.middleware.CorsMiddleware",

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE","UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


AUTH_USER_MODEL = 'accounts.User'


APPEND_SLASH = False


# Rest Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Swagger Conf
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS':{
        'Bearer' : {
            'type' : 'apiKey',
            'name' : 'Authorization',
            'in' : 'header',
        }
    }
        
}



# DRF E-Commerce
DRF_ECOMMERCE = {
    "COMMENTS" : {
        'MAX_DEPTH' : 3,
        'ALLOWED_NESTED_REPLY' : True,
        'USER_CAN_DELETE' : True,
        'USER_CAN_UPDATE' : True,
    },
    "ORDERS" : {
        "MAXIMUM_PRODUCT_QUANTITY" : 3,
        "USER_CAN_DELETE_ORDER" : True,
    },
    "PAYMENT" : {
        "SUCCESS_URL":"youre.exp/path/",
        "FAIL_URL" : "youre.exp/path",
        "CALLBACK_URL" : "https://youredomain.exp/payment/callback-payment/",
        # Add another settings exp. MERCAHNT_ID for payment getway
    }
}



# # Cors allowed  origin 
CORS_ALLOWED_ORIGINS = []
for cors_allowed_origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(","):
    if cors_allowed_origin.strip():
        CORS_ALLOWED_ORIGINS.append(cors_allowed_origin.strip())

CORS_ALLOW_CREDENTIALS = True