# Generated by Django 6.0.1 on 2026-01-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='percent_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
