# Generated by Django 6.0.1 on 2026-01-31 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.comment'),
        ),
    ]
