# Generated by Django 6.0.1 on 2026-02-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_comment_replyed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
